config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path(
        "",
        login_required(TemplateView.as_view(template_name="pages/home.html")),
        name="home",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("tracing_app.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path("", include("tracing_app.adoptions.urls", namespace="adoptions")),
    path("", include("tracing_app.pets.urls", namespace="pets")),
    path("", include("tracing_app.adopters.urls", namespace="adopters")),
    path("", include("tracing_app.tasks.urls", namespace="tasks")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

tracing_app/pets/urls.py
from django.urls import path

from .views import PetListView, PetCreateView, PetUpdateView

app_name = "pets"
urlpatterns = [
    path("pets/", PetListView.as_view(), name="pets-list"),
    path("pets/new", PetCreateView.as_view(), name="pets-new"),
    path("pets/<int:pk>", PetUpdateView.as_view(), name="pets-edit"),
]

tracing_app/tasks/urls.py
from django.urls import path

from .views import (
    TaskCreateView,
    TaskUpdateView,
    CompleteTaskView,
    DoneTaskView,
    ReminderCreateView,
    NotifyView,
    ConfigurationsListView,
    ConfigurationTaskCreateView,
    ConfigurationReminderCreateView,
    ConfigurationsUpdateView,
)

app_name = "tasks"
urlpatterns = [
    path("tasks/<int:adpotion>/new", TaskCreateView.as_view(), name="task-new"),
    path(
        "reminder/<int:adpotion>/new", ReminderCreateView.as_view(), name="reminder-new"
    ),
    path("tasks/<int:adpotion>/<int:pk>", TaskUpdateView.as_view(), name="task-edit"),
    path("notify/<int:task>", NotifyView.as_view(), name="task-notify"),
    path("t/<uuid:uuid>", CompleteTaskView.as_view(), name="public-task"),
    path("t/done", DoneTaskView.as_view(), name="done-task"),
    path("configurations/", ConfigurationsListView.as_view(), name="config-list"),
    path("reminders/new", ConfigurationReminderCreateView.as_view(), name="remin-new"),
    path(
        "configurations/new", ConfigurationTaskCreateView.as_view(), name="config-new"
    ),
    path(
        "configurations/<int:pk>",
        ConfigurationsUpdateView.as_view(),
        name="config-edit",
    ),
]

tracing_app/users/urls.py
from django.urls import path

from tracing_app.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

tracing_app/adopters/models.py
from django.db import models
from django.utils import timezone


class Adopter(models.Model):
    TYPE_DOCUMENT = [("CC", "Cedula"), ("TI", "Tarjeta de identidad")]
    GENDER = [("F", "Femenino"), ("M", "Masculino"), ("O", "Otro")]
    first_name = models.CharField(max_length=30, verbose_name="Nombres")
    last_name = models.CharField(max_length=150, verbose_name="Apellidos")
    phone = models.CharField(max_length=50, verbose_name="Telefono")
    other_phone = models.CharField(
        max_length=50,
        blank=True,
        verbose_name="Otro telefono",
    )
    address = models.CharField(
        max_length=100,
        verbose_name="Direccion",
    )
    id_document = models.CharField(
        max_length=20,
        verbose_name="Numero de documento",
    )
    gender = models.CharField(
        max_length=2,
        choices=GENDER,
        default="M",
        verbose_name="Genero",
    )
    email = models.EmailField(max_length=254, verbose_name="Correo electrónico")
    type_document = models.CharField(
        verbose_name="Tipo de documento",
        max_length=2,
        choices=TYPE_DOCUMENT,
        default="CC",
    )

    def __str__(self):
        return f"{self.first_name} - {self.id_document}"

tracing_app/pets/models.py
from django.db import models
from django.utils import timezone


class Pet(models.Model):
    name = models.CharField(max_length=30, verbose_name="Nombre")
    age = models.PositiveSmallIntegerField(verbose_name="Edad")
    disability = models.BooleanField(default=False, verbose_name="Discapacidad")
    comments = models.TextField(verbose_name="Comentarios")

    def __str__(self):
        return f"{self.name} - {self.age} años"

tracing_app/adopters/forms.py
from django.forms import ModelForm
from django import forms
from .models import Adopter


class CreateAdopterForm(ModelForm):
    class Meta:
        model = Adopter
        fields = [
            "first_name",
            "last_name",
            "gender",
            "type_document",
            "id_document",
            "address",
            "email",
            "phone",
            "other_phone",
        ]

tracing_app/adoptions/forms.py
from django.forms import ModelForm
from django import forms
from .models import Adoption
from crispy_forms.layout import Submit
from crispy_forms.helper import FormHelper


class BaseCrispy(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()

        self.helper.add_input(Submit("submit", "Guardar"))


class CreateAdoptionForm(BaseCrispy):
    class Meta:
        model = Adoption
        fields = [
            "date",
            "status",
            "adopter",
            "pet",
        ]


class EditAdoptionForm(BaseCrispy):
    class Meta:
        model = Adoption
        fields = [
            "status",
        ]

tracing_app/pets/forms.py
from django.forms import ModelForm
from django import forms
from crispy_forms.layout import Submit
from crispy_forms.helper import FormHelper
from .models import Pet


class BaseCrispy(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()

        self.helper.add_input(Submit("submit", "Guardar"))


class CreatePetForm(BaseCrispy):
    class Meta:
        model = Pet
        fields = [
            "name",
            "age",
            "disability",
            "comments",
        ]

tracing_app/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):

    error_message = admin_forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

tracing_app/adopters/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from .models import Adopter
from .forms import CreateAdopterForm


class AdopterListView(LoginRequiredMixin, ListView):
    model = Adopter

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class AdopterCreateView(LoginRequiredMixin, CreateView):
    model = Adopter
    form_class = CreateAdopterForm

    def get_success_url(self):
        return reverse("adopters:adopter-list")


class AdopterUpdateView(LoginRequiredMixin, UpdateView):
    model = Adopter
    form_class = CreateAdopterForm

    def get_success_url(self):
        return reverse("adopters:adopter-list")

tracing_app/adoptions/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse
from tracing_app.tasks.models import Task
from tracing_app.tasks.tasks import create_tasks
from .models import Adoption
from .forms import CreateAdoptionForm, EditAdoptionForm
from django.contrib.auth.mixins import LoginRequiredMixin


class AdoptionListView(LoginRequiredMixin, ListView):
    model = Adoption

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class AdoptionCreateView(LoginRequiredMixin, CreateView):
    model = Adoption
    form_class = CreateAdoptionForm

    def get_success_url(self):
        return reverse("adoptions:adoption-list")

    def form_valid(self, form):
        url = super(AdoptionCreateView, self).form_valid(form)
        create_tasks.apply((self.object.id,))
        return url


class AdoptionUpdateView(LoginRequiredMixin, UpdateView):
    model = Adoption
    form_class = EditAdoptionForm

    def get_success_url(self):
        return reverse("adoptions:adoption-list")

    def get_context_data(self, **kwargs):
        context = super(AdoptionUpdateView, self).get_context_data(**kwargs)
        context["task_list"] = (
            Task.objects.filter(
                adopcion=self.object,
            )
            .exclude(status__in=["canceled"])
            .order_by("date_start")
        )

        return context

tracing_app/pets/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse
from .models import Pet
from .forms import CreatePetForm
from django.contrib.auth.mixins import LoginRequiredMixin


class PetListView(LoginRequiredMixin, ListView):
    model = Pet

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["message"] = "hello"
        return context


class PetCreateView(LoginRequiredMixin, CreateView):
    model = Pet
    form_class = CreatePetForm

    def get_success_url(self):
        return reverse("pets:pets-list")


class PetUpdateView(LoginRequiredMixin, UpdateView):
    model = Pet
    form_class = CreatePetForm

    def get_success_url(self):
        return reverse("pets:pets-list")

tracing_app/tasks/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect
from django.views.generic.base import View
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse
from tracing_app.adoptions.models import Adoption
from .models import Task, Configuration
from .forms import (
    CreateTaskForm,
    CompleteMultimediaTask,
    CompleteTextTask,
    EditTaskForm,
    CreateReminderForm,
    ConfigurationTaskForm,
    ConfigurationReminderForm,
    EditConfigurationTaskForm,
    EditConfigurationReminderForm,
)
from django.views.generic.base import TemplateView
from django.http import Http404
from .tasks import send_notification, create_notifications
from django.contrib.auth.mixins import LoginRequiredMixin


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    form_class = CreateTaskForm

    def setup(self, request, *args, **kwargs):
        super(TaskCreateView, self).setup(request, *args, **kwargs)
        self.adoption = get_object_or_404(Adoption, id=self.kwargs["adpotion"])

    def get_form_kwargs(self):
        kwargs = super(TaskCreateView, self).get_form_kwargs()
        if "data" in kwargs:
            data = kwargs["data"].copy()
            data.appendlist("adopcion", self.adoption)
            kwargs["data"] = data
        return kwargs

    def form_valid(self, form):
        url = super(TaskCreateView, self).form_valid(form)
        create_notifications(self.object.id)
        return url

    def get_success_url(self):
        return reverse("adoptions:adoption-edit", args=(self.adoption.id,))


class ReminderCreateView(TaskCreateView):
    form_class = CreateReminderForm

    def get_form_kwargs(self):
        kwargs = super(ReminderCreateView, self).get_form_kwargs()
        if "data" in kwargs:
            data = kwargs["data"].copy()
            data.appendlist("type", "reminder")
            kwargs["data"] = data
        return kwargs


class NotifyView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        pid = kwargs["task"]
        task = get_object_or_404(Task, id=pid)
        send_notification(task.id)

        return redirect(reverse("tasks:task-edit", args=(task.adopcion.id, task.id)))


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    form_class = EditTaskForm

    def setup(self, request, *args, **kwargs):
        super(TaskUpdateView, self).setup(request, *args, **kwargs)
        self.adoption = get_object_or_404(Adoption, id=self.kwargs["adpotion"])

    def get_success_url(self):
        return reverse("adoptions:adoption-edit", args=(self.adoption.id,))


class CompleteTaskView(UpdateView):
    model = Task
    form_class = CreateTaskForm
    slug_field = "uuid"
    slug_url_kwarg = "uuid"
    template_name = "pages/public.html"

    def get_success_url(self):
        return reverse("tasks:done-task")

    def get_form_kwargs(self):
        kwargs = super(CompleteTaskView, self).get_form_kwargs()
        if "data" in kwargs:
            data = kwargs["data"].copy()
            data.appendlist("status", "finished")
            kwargs["data"] = data
        return kwargs

    def get_form_class(self):
        task = self.object
        if task.type == "multimedia":
            return CompleteMultimediaTask
        elif task.type == "text":
            return CompleteTextTask
        else:
            return super(CompleteTaskView, self).get_form_class()


class DoneTaskView(TemplateView):
    template_name = "pages/done.html"


class ConfigurationsListView(LoginRequiredMixin, ListView):
    model = Configuration


class ConfigurationTaskCreateView(LoginRequiredMixin, CreateView):
    model = Configuration
    form_class = ConfigurationTaskForm

    def get_success_url(self):
        return reverse("tasks:config-list")


class ConfigurationReminderCreateView(ConfigurationTaskCreateView):
    form_class = ConfigurationReminderForm

    def get_form_kwargs(self):
        kwargs = super(ConfigurationReminderCreateView, self).get_form_kwargs()
        if "data" in kwargs:
            data = kwargs["data"].copy()
            data.appendlist("type", "reminder")
            kwargs["data"] = data
        return kwargs

    def get_success_url(self):
        return reverse("tasks:config-list")


class ConfigurationsUpdateView(LoginRequiredMixin, UpdateView):
    model = Configuration

    def get_success_url(self):
        return reverse("tasks:config-list")

    def get_form_class(self):
        task = self.object
        if task.type in ["multimedia", "text"]:
            return EditConfigurationTaskForm
        elif task.type == "reminder":
            return EditConfigurationReminderForm
        else:
            return super(ConfigurationsUpdateView, self).get_form_class()

tracing_app/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

tracing_app/templates/tasks/configuration_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Crear Configuración{% endblock %}
{% block nav_title %}Crear Configuración{% endblock %}
{% block content %}

<div class="row">
    <div class="col-md-1"></div>
  <div class="col-md-10">
    <div class="card card-user">
        <br/>
        <div class="row">
            <div class="col-md-4 pr-1">
            </div>
            
            <div class="col-md-4 pr-1" style="text-align:center" >
            <h5 class="card-title" style="margin-top: 20px;">Configuración</h5>
            </div>
            <div class="col-md-4 pr-1">
            </div>
        </div>
        <div class="card-body">
            {% crispy form %}
        </div>
    </div>
  </div>
<div class="col-md-1"></div>



{% endblock %}

tracing_app/templates/tasks/configuration_list.html
{% extends "base.html" %}
{% block title %}Configuraciones de tareas{% endblock %}
{% block nav_title %}Configuraciones de tareas{% endblock %}

{% block content %}
    
    <div class="card">
        <div class="card-body pb-0">
            <div class="row">
                <div class="col-md-6 pr-4">
                    <h4 class="card-title">Configuraciones</h4>
                </div>
               
                <div class="col-md-3 pl-1 d-flex justify-content-end align-items-center">
                    <a href="{% url 'tasks:config-new' %}" class="btn btn-primary btn-round  btn-block">Crear configuración tarea</a>
                </div>
                <div class="col-md-3 pl-1 d-flex justify-content-end align-items-center">
                  <a href="{% url 'tasks:remin-new' %}" class="btn btn-primary btn-round  btn-block">Crear configuración recordatorio</a>
              </div>
            </div>
        
            <div class="table-responsive pb-0">
                <table class="table mb-0">
                    <thead class=" text-primary">
                        <tr>
                            <th> configuración </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for config in object_list %}
                            <tr class="clickable-row" data-href="{% url  'tasks:config-edit' config.pk %}">
                                <td>{{ config }} </td>
                            </tr> 
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer pt-0">
            <hr>
            <div class="m-2 d-flex d-flex justify-content-between">
                {% if object_list.has_previous %}
                    <a class="card-link" rel="keep-params" href="?{{base_url }}&page=1">Primero</a>
                    <a class="card-link" rel="keep-params" href="?{{base_url }}&page={{ object_list.previous_page_number }}">Anterior</a>
                {% endif %}
        
                <span class="current">
                    Página {{ object_list.number }} de {{ object_list.paginator.num_pages }}.
                </span>
        
                {% if object_list.has_next %}
                    <a class="card-link" rel="keep-params" href="?{{base_url }}&page={{ object_list.next_page_number }}">Siguiente</a>
                    <a class="card-link" rel="keep-params" href="?{{base_url }}&page={{ object_list.paginator.num_pages }}">Último</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

tracing_app/templates/tasks/task_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Crear Tarea{% endblock %}
{% block nav_title %}Crear Tarea{% endblock %}
{% block content %}

{% if object %}
<div class="card">
  <div class="card-body pb-0">
    <div class="row">
      <div class="col-md-9 pr-4">
        <h4 class="card-title">Registro</h4>
      </div>
      <div class="col-md-3 pl-1 d-flex justify-content-end align-items-center">
        <form action="{% url 'tasks:task-notify' object.id %}" method="POST">
          {% csrf_token %}
          <button class="btn btn-primary btn-round btn-block">Enviar notificacion</button>
        </form>
      </div>
    </div>
    <div class="row">
      <div class="col text-center">
        {% if object.type == "multimedia" %}
          {% if object.file_path %}
            {% if "jpg" in object.file_path.name or "png" in object.file_path.name or "jpeg" in object.file_path.name %}
            <img src="{{ object.file_path.url }}" alt="">
            {% else %}
              <video width="320" height="240" controls>
                <source src="{{ object.file_path.url }}">
              </video>
            {% endif %}
    
          {% else %}
            <p>Aun no hay registro de la tarea.</p>
          {% endif %}
        {% else %}
          <p>{{ object.text }}</p>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endif %}

<div class="row">
    <div class="col-md-1"></div>
  <div class="col-md-10">
    <div class="card card-user">
        <br/>
        <div class="row">
            <div class="col-md-4 pr-1">
            </div>
            
            <div class="col-md-4 pr-1" style="text-align:center" >
            <h5 class="card-title" style="margin-top: 20px;">Tarea</h5>
            </div>
            <div class="col-md-4 pr-1">
            </div>
        </div>
        <div class="card-body">
            {% crispy form %}
        </div>
    </div>
  </div>
<div class="col-md-1"></div>



{% endblock %}

tracing_app/templates/tasks/task_list.html
{% extends "base.html" %}
{% block title %}Tareas{% endblock %}
{% block nav_title %}Tareas{% endblock %}

{% block content %}
    
    <div class="card">
        <div class="card-body pb-0">
            <div class="row">
                <div class="col-md-9 pr-4">
                    <h4 class="card-title">Tareas</h4>
                    
                </div>
               
                <div class="col-md-3 pl-1 d-flex justify-content-end align-items-center">
                    <a href="{% url 'tasks:task-new' %}" class="btn btn-primary btn-round  btn-block">Crear Tarea</a>
                </div>
            </div>
        
            <div class="table-responsive pb-0">
                <table class="table mb-0">
                    <thead class=" text-primary">
                        <tr>
                            <th> Tarea </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in task_list %}
                            <tr class="clickable-row" data-href="{% url  'tasks:task-edit' task.pk %}">
                                <td>{{ task }} </td>
                            </tr> 
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer pt-0">
            <hr>
            <div class="m-2 d-flex d-flex justify-content-between">
                {% if task_list.has_previous %}
                    <a class="card-link" rel="keep-params" href="?{{base_url }}&page=1">Primero</a>
                    <a class="card-link" rel="keep-params" href="?{{base_url }}&page={{ task_list.previous_page_number }}">Anterior</a>
                {% endif %}
        
                <span class="current">
                    Página {{ task_list.number }} de {{ task_list.paginator.num_pages }}.
                </span>
        
                {% if task_list.has_next %}
                    <a class="card-link" rel="keep-params" href="?{{base_url }}&page={{ task_list.next_page_number }}">Siguiente</a>
                    <a class="card-link" rel="keep-params" href="?{{base_url }}&page={{ task_list.paginator.num_pages }}">Último</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}